### ISSUE TITLE
 SyntaxError: Unexpected token ... (/node_modules/react-dev-utils/node_modules/globby/index.js:49)

### ISSUE THREAD

**Issue by gameme10** [PyPet/PyPetJS#4]
**¿Que bug tienes?**
React no inicia
**Para reproducir**
1. 'inicia la app'
4. ¡Aquí Aparece el error!

 - Version: Node v6.14.4 - NPM v3.10.10 - PyPetJS 3b60ef919faaeb34f8006024c78e8315

**LOGS**

 > pypet-js@0.1.0 start /usr/src/app
 > react-scripts start
 
 /usr/src/app/node_modules/react-dev-utils/node_modules/globby/index.js:49
                 ...taskOptions
                 ^^^
 
 SyntaxError: Unexpected token ...
     at createScript (vm.js:56:10)
     at Object.runInThisContext (vm.js:97:10)
     at Module._compile (module.js:549:28)
     at Object.Module._extensions..js (module.js:586:10)
     at Module.load (module.js:494:32)
     at tryModuleLoad (module.js:453:12)
     at Function.Module._load (module.js:445:3)
     at Module.require (module.js:504:17)
     at require (internal/module.js:20:19)
     at Object.<anonymous> (/usr/src/app/node_modules/react-dev-utils/globby.js:10:14) 
npm ERR! Linux 5.4.83-v8
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.14.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! pypet-js@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pypet-js@0.1.0 start script 'react-scripts start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pypet-js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pypet-js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pypet-js
npm ERR! There is likely additional logging output above. 
npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log

**Comment by gameme10** [comment]
### Solución:
Update a Node 14.15.4-buster-run [Ver Fuente](https://stackoverflow.com/a/65626623)

**Comment by gameme10** [comment]
Reparado.
